name:                kernmantle
version:             0.1.0.0
github:              "YPares/kernmantle"
license:             BSD3
author:              "Yves Parès"
maintainer:          "yves.pares@gmail.com"
copyright:           "2019 Yves Parès"

# Metadata used when publishing your package
synopsis:            Composing Applicatives, Monads, Comonads and Arrows into Arrows
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YPares/kernmantle#readme>

dependencies:
- base >= 4.7 && < 5
- bifunctors
- profunctors >= 5.5.2 # Needed to have the whole set of Cayley instances
- vinyl >= 0.11
- transformers
- safe-exceptions

library:
  source-dirs: src

executables:
  ex1:
    main: examples/Ex1.hs
    dependencies:
      - kernmantle
  exBypass:
    main: examples/ExBypass.hs
    dependencies:
      - kernmantle
  exCli:
    main: examples/ExCli.hs
    dependencies:
      - kernmantle
      - optparse-applicative
      - profunctors
      - bytestring
  exLenses:
    main: examples/ExLenses.hs
    dependencies:
      - kernmantle
      - profunctors
      - lens
      - unordered-containers
      - aeson
      - lens-aeson
